using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Loaders.Obfuscation.Utilities;

namespace Loaders.Obfuscation.Services
{
    internal static class StringResourceLoaderGenerator
    {
        public static string Generate(
            string generatedNamespace,
            string generatedTypeName,
            string manifestResourceName,
            IReadOnlyCollection<byte> usedCodecIds)
        {
            if (string.IsNullOrWhiteSpace(generatedNamespace))
            {
                throw new ArgumentException("Generated namespace is required.", nameof(generatedNamespace));
            }

            if (string.IsNullOrWhiteSpace(generatedTypeName))
            {
                throw new ArgumentException("Generated type name is required.", nameof(generatedTypeName));
            }

            if (string.IsNullOrWhiteSpace(manifestResourceName))
            {
                throw new ArgumentException("Manifest resource name is required.", nameof(manifestResourceName));
            }

            var codecs = new HashSet<byte>(usedCodecIds ?? Array.Empty<byte>());
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// String resource format v1: LSR1 header, sorted descriptors, metadata region, payload region.");
            builder.AppendLine("namespace " + generatedNamespace);
            builder.AppendLine("{");
            builder.AppendLine("    internal static class " + generatedTypeName);
            builder.AppendLine("    {");
            builder.AppendLine("        private const int Magic = " + StringResourceSerializer.Magic.ToString(CultureInfo.InvariantCulture) + ";");
            builder.AppendLine("        private const int Version = " + StringResourceSerializer.FormatVersion.ToString(CultureInfo.InvariantCulture) + ";");
            builder.AppendLine("        private const int HeaderSize = " + StringResourceSerializer.HeaderSize.ToString(CultureInfo.InvariantCulture) + ";");
            builder.AppendLine("        private const int DescriptorSize = " + StringResourceSerializer.DescriptorSize.ToString(CultureInfo.InvariantCulture) + ";");
            builder.AppendLine("        private const string ResourceName = " + Quote(manifestResourceName) + ";");
            builder.AppendLine("        private static readonly object InitLock = new object();");
            builder.AppendLine("        private static readonly object CacheLock = new object();");
            builder.AppendLine("        private static byte[] Blob;");
            builder.AppendLine("        private static Entry[] Entries;");
            builder.AppendLine("        private static string[] Cache;");
            builder.AppendLine();
            builder.AppendLine("        internal static string Get(int token)");
            builder.AppendLine("        {");
            builder.AppendLine("            EnsureInitialized();");
            builder.AppendLine("            var entryIndex = FindEntry(token);");
            builder.AppendLine("            if (entryIndex < 0)");
            builder.AppendLine("            {");
            builder.AppendLine("                throw new System.InvalidOperationException(\"String resource entry was not found for token 0x\" + unchecked((uint)token).ToString(\"X8\", System.Globalization.CultureInfo.InvariantCulture) + \".\");");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            var entry = Entries[entryIndex];");
            builder.AppendLine("            var cached = Cache[entry.CacheIndex];");
            builder.AppendLine("            if (cached != null)");
            builder.AppendLine("            {");
            builder.AppendLine("                return cached;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            lock (CacheLock)");
            builder.AppendLine("            {");
            builder.AppendLine("                cached = Cache[entry.CacheIndex];");
            builder.AppendLine("                if (cached == null)");
            builder.AppendLine("                {");
            builder.AppendLine("                    cached = Decode(entry);");
            builder.AppendLine("                    Cache[entry.CacheIndex] = cached;");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                return cached;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
            AppendInitialization(builder, generatedTypeName);
            AppendDecode(builder, codecs);
            AppendCodecMethods(builder, codecs);
            AppendCommonHelpers(builder, codecs);
            AppendEntryType(builder);
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void AppendInitialization(StringBuilder builder, string generatedTypeName)
        {
            builder.AppendLine("        private static void EnsureInitialized()");
            builder.AppendLine("        {");
            builder.AppendLine("            if (Entries != null)");
            builder.AppendLine("            {");
            builder.AppendLine("                return;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            lock (InitLock)");
            builder.AppendLine("            {");
            builder.AppendLine("                if (Entries != null)");
            builder.AppendLine("                {");
            builder.AppendLine("                    return;");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                var assembly = typeof(" + generatedTypeName + ").Assembly;");
            builder.AppendLine("                using (var stream = assembly.GetManifestResourceStream(ResourceName))");
            builder.AppendLine("                {");
            builder.AppendLine("                    if (stream == null)");
            builder.AppendLine("                    {");
            builder.AppendLine("                        throw new System.InvalidOperationException(\"String resource '\" + ResourceName + \"' was not found in assembly '\" + assembly.FullName + \"'.\");");
            builder.AppendLine("                    }");
            builder.AppendLine();
            builder.AppendLine("                    using (var memory = new System.IO.MemoryStream())");
            builder.AppendLine("                    {");
            builder.AppendLine("                        stream.CopyTo(memory);");
            builder.AppendLine("                        Blob = memory.ToArray();");
            builder.AppendLine("                    }");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                ParseIndex();");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static void ParseIndex()");
            builder.AppendLine("        {");
            builder.AppendLine("            if (Blob == null || Blob.Length < HeaderSize)");
            builder.AppendLine("            {");
            builder.AppendLine("                throw new System.InvalidOperationException(\"String resource is truncated before the header.\");");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            var magic = ReadInt32(Blob, 0);");
            builder.AppendLine("            var version = ReadInt32(Blob, 4);");
            builder.AppendLine("            var recordCount = ReadInt32(Blob, 12);");
            builder.AppendLine("            var descriptorOffset = ReadInt32(Blob, 16);");
            builder.AppendLine("            var descriptorLength = ReadInt32(Blob, 20);");
            builder.AppendLine("            var metadataOffset = ReadInt32(Blob, 24);");
            builder.AppendLine("            var metadataLength = ReadInt32(Blob, 28);");
            builder.AppendLine("            var payloadOffset = ReadInt32(Blob, 32);");
            builder.AppendLine("            var payloadLength = ReadInt32(Blob, 36);");
            builder.AppendLine();
            builder.AppendLine("            if (magic != Magic || version != Version)");
            builder.AppendLine("            {");
            builder.AppendLine("                throw new System.InvalidOperationException(\"String resource has an unsupported format.\");");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            if (recordCount < 0 || descriptorOffset != HeaderSize || descriptorLength != checked(recordCount * DescriptorSize))");
            builder.AppendLine("            {");
            builder.AppendLine("                throw new System.InvalidOperationException(\"String resource index header is invalid.\");");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            ValidateRange(descriptorOffset, descriptorLength, Blob.Length, \"descriptor table\");");
            builder.AppendLine("            ValidateRange(metadataOffset, metadataLength, Blob.Length, \"metadata region\");");
            builder.AppendLine("            ValidateRange(payloadOffset, payloadLength, Blob.Length, \"payload region\");");
            builder.AppendLine();
            builder.AppendLine("            var entries = new Entry[recordCount];");
            builder.AppendLine("            var previousToken = int.MinValue;");
            builder.AppendLine("            for (var i = 0; i < recordCount; i++)");
            builder.AppendLine("            {");
            builder.AppendLine("                var offset = descriptorOffset + i * DescriptorSize;");
            builder.AppendLine("                var entry = new Entry(");
            builder.AppendLine("                    ReadInt32(Blob, offset),");
            builder.AppendLine("                    ReadInt32(Blob, offset + 4),");
            builder.AppendLine("                    ReadInt32(Blob, offset + 8),");
            builder.AppendLine("                    ReadInt32(Blob, offset + 12),");
            builder.AppendLine("                    ReadInt32(Blob, offset + 16),");
            builder.AppendLine("                    ReadInt32(Blob, offset + 20),");
            builder.AppendLine("                    ReadInt32(Blob, offset + 24),");
            builder.AppendLine("                    ReadInt32(Blob, offset + 28),");
            builder.AppendLine("                    ReadInt32(Blob, offset + 32),");
            builder.AppendLine("                    unchecked((uint)ReadInt32(Blob, offset + 36)));");
            builder.AppendLine();
            builder.AppendLine("                if (i > 0 && entry.Token <= previousToken)");
            builder.AppendLine("                {");
            builder.AppendLine("                    throw new System.InvalidOperationException(\"String resource descriptor tokens are not sorted.\");");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                if (entry.CacheIndex < 0 || entry.CacheIndex >= recordCount || entry.DecodedCharLength < 0)");
            builder.AppendLine("                {");
            builder.AppendLine("                    throw new System.InvalidOperationException(\"String resource descriptor cache index or length is invalid.\");");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                ValidateRange(entry.MetadataOffset, entry.MetadataLength, Blob.Length, \"record metadata\");");
            builder.AppendLine("                ValidateRange(entry.PayloadOffset, entry.PayloadLength, Blob.Length, \"record payload\");");
            builder.AppendLine("                entries[i] = entry;");
            builder.AppendLine("                previousToken = entry.Token;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            Entries = entries;");
            builder.AppendLine("            Cache = new string[recordCount];");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static int FindEntry(int token)");
            builder.AppendLine("        {");
            builder.AppendLine("            var low = 0;");
            builder.AppendLine("            var high = Entries.Length - 1;");
            builder.AppendLine("            while (low <= high)");
            builder.AppendLine("            {");
            builder.AppendLine("                var middle = low + ((high - low) / 2);");
            builder.AppendLine("                var current = Entries[middle].Token;");
            builder.AppendLine("                if (current == token)");
            builder.AppendLine("                {");
            builder.AppendLine("                    return middle;");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                if (current < token)");
            builder.AppendLine("                {");
            builder.AppendLine("                    low = middle + 1;");
            builder.AppendLine("                }");
            builder.AppendLine("                else");
            builder.AppendLine("                {");
            builder.AppendLine("                    high = middle - 1;");
            builder.AppendLine("                }");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return -1;");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        private static void AppendDecode(StringBuilder builder, ISet<byte> codecs)
        {
            builder.AppendLine("        private static string Decode(Entry entry)");
            builder.AppendLine("        {");
            builder.AppendLine("            var metadata = Slice(Blob, entry.MetadataOffset, entry.MetadataLength);");
            builder.AppendLine("            var payload = Slice(Blob, entry.PayloadOffset, entry.PayloadLength);");
            builder.AppendLine("            byte[] decoded;");
            builder.AppendLine("            switch (entry.CodecId)");
            builder.AppendLine("            {");

            foreach (var codecId in codecs.OrderBy(id => id))
            {
                builder.AppendLine("                case " + codecId.ToString(CultureInfo.InvariantCulture) + ":");
                builder.AppendLine("                    decoded = DecodeCodec" + codecId.ToString(CultureInfo.InvariantCulture) + "(metadata, payload, entry.DecodedCharLength);");
                builder.AppendLine("                    break;");
            }

            builder.AppendLine("                default:");
            builder.AppendLine("                    throw new System.InvalidOperationException(\"String resource codec \" + entry.CodecId.ToString(System.Globalization.CultureInfo.InvariantCulture) + \" is not supported by this loader.\");");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            var expectedBytes = checked(entry.DecodedCharLength * 2);");
            builder.AppendLine("            if (decoded.Length != expectedBytes)");
            builder.AppendLine("            {");
            builder.AppendLine("                throw new System.InvalidOperationException(\"String resource decoder returned an unexpected length.\");");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            if (ComputeFnv1a32(decoded) != entry.Checksum)");
            builder.AppendLine("            {");
            builder.AppendLine("                throw new System.InvalidOperationException(\"String resource checksum validation failed.\");");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return StringFromUtf16Le(decoded, entry.DecodedCharLength);");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        private static void AppendCodecMethods(StringBuilder builder, ISet<byte> codecs)
        {
            if (codecs.Contains(1))
            {
                builder.AppendLine("        private static byte[] DecodeCodec1(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            if (metadata.Length == 0) throw new System.InvalidOperationException(\"Invalid XOR metadata.\");");
                builder.AppendLine("            var output = new byte[payload.Length];");
                builder.AppendLine("            for (var i = 0; i < payload.Length; i++) output[i] = (byte)(payload[i] ^ metadata[i % metadata.Length]);");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(2))
            {
                builder.AppendLine("        private static byte[] DecodeCodec2(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            if (metadata.Length != 4) throw new System.InvalidOperationException(\"Invalid LCG metadata.\");");
                builder.AppendLine("            var output = Clone(payload);");
                builder.AppendLine("            ApplyLcgXor(output, ReadUInt32(metadata, 0));");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(3))
            {
                builder.AppendLine("        private static byte[] DecodeCodec3(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            if (metadata.Length != 0) throw new System.InvalidOperationException(\"Invalid GZip metadata.\");");
                builder.AppendLine("            return Decompress(payload);");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(4))
            {
                builder.AppendLine("        private static byte[] DecodeCodec4(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            if (metadata.Length != 4) throw new System.InvalidOperationException(\"Invalid GZip LCG metadata.\");");
                builder.AppendLine("            var output = Clone(payload);");
                builder.AppendLine("            ApplyLcgXor(output, ReadUInt32(metadata, 0));");
                builder.AppendLine("            return Decompress(output);");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(5))
            {
                builder.AppendLine("        private static byte[] DecodeCodec5(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            if (metadata.Length != 1) throw new System.InvalidOperationException(\"Invalid reverse XOR metadata.\");");
                builder.AppendLine("            var output = new byte[payload.Length];");
                builder.AppendLine("            for (var i = 0; i < payload.Length; i++) output[i] = (byte)(payload[payload.Length - i - 1] ^ metadata[0]);");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(6))
            {
                builder.AppendLine("        private static byte[] DecodeCodec6(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            if (metadata.Length != 8) throw new System.InvalidOperationException(\"Invalid decimal delta metadata.\");");
                builder.AppendLine("            var expected = checked(charCount * 2);");
                builder.AppendLine("            if (payload.Length != checked(expected * 2)) throw new System.InvalidOperationException(\"Invalid decimal delta payload length.\");");
                builder.AppendLine("            var seed = ReadInt32(metadata, 0);");
                builder.AppendLine("            var step = ReadInt32(metadata, 4);");
                builder.AppendLine("            var output = new byte[expected];");
                builder.AppendLine("            for (var i = 0; i < output.Length; i++)");
                builder.AppendLine("            {");
                builder.AppendLine("                var encoded = ReadUInt16(payload, i * 2);");
                builder.AppendLine("                var mask = 256 + (int)((seed + (long)i * step) % 997);");
                builder.AppendLine("                output[i] = checked((byte)(encoded - mask));");
                builder.AppendLine("            }");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(7))
            {
                builder.AppendLine("        private static byte[] DecodeCodec7(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            if (metadata.Length != 0 || payload.Length != checked(charCount * 8)) throw new System.InvalidOperationException(\"Invalid UTF-16 delta payload.\");");
                builder.AppendLine("            var output = new byte[checked(charCount * 2)];");
                builder.AppendLine("            for (var i = 0; i < charCount; i++)");
                builder.AppendLine("            {");
                builder.AppendLine("                var masked = ReadUInt32(payload, i * 8);");
                builder.AppendLine("                var delta = ReadUInt32(payload, i * 8 + 4);");
                builder.AppendLine("                WriteChar(output, i, checked((ushort)(masked - delta)));");
                builder.AppendLine("            }");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(8))
            {
                builder.AppendLine("        private static byte[] DecodeCodec8(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            if (metadata.Length != 0 || payload.Length != checked(charCount * 12)) throw new System.InvalidOperationException(\"Invalid shuffled UTF-16 payload.\");");
                builder.AppendLine("            var output = new byte[checked(charCount * 2)];");
                builder.AppendLine("            for (var row = 0; row < charCount; row++)");
                builder.AppendLine("            {");
                builder.AppendLine("                var offset = row * 12;");
                builder.AppendLine("                var index = checked((int)ReadUInt32(payload, offset));");
                builder.AppendLine("                if (index < 0 || index >= charCount) throw new System.InvalidOperationException(\"Invalid shuffled UTF-16 index.\");");
                builder.AppendLine("                var masked = ReadUInt32(payload, offset + 4);");
                builder.AppendLine("                var mask = ReadUInt32(payload, offset + 8);");
                builder.AppendLine("                WriteChar(output, index, checked((ushort)(masked ^ mask)));");
                builder.AppendLine("            }");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(9))
            {
                builder.AppendLine("        private static byte[] DecodeCodec9(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            var expected = checked(charCount * 2);");
                builder.AppendLine("            if (metadata.Length != 0 || payload.Length != checked(expected * 2)) throw new System.InvalidOperationException(\"Invalid interleaved payload.\");");
                builder.AppendLine("            var output = new byte[expected];");
                builder.AppendLine("            for (var i = 0; i < output.Length; i++) output[i] = (byte)(payload[i * 2] ^ payload[i * 2 + 1]);");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(10))
            {
                builder.AppendLine("        private static byte[] DecodeCodec10(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            if (metadata.Length != 2) throw new System.InvalidOperationException(\"Invalid affine metadata.\");");
                builder.AppendLine("            var inverse = metadata[0];");
                builder.AppendLine("            var offset = metadata[1];");
                builder.AppendLine("            var output = new byte[payload.Length];");
                builder.AppendLine("            for (var i = 0; i < payload.Length; i++) output[i] = (byte)(((payload[i] - offset) * inverse) & 255);");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(11))
            {
                builder.AppendLine("        private static byte[] DecodeCodec11(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            var expected = checked(charCount * 2);");
                builder.AppendLine("            if (payload.Length != expected || metadata.Length != checked(expected * 4)) throw new System.InvalidOperationException(\"Invalid byte permutation payload.\");");
                builder.AppendLine("            var output = new byte[expected];");
                builder.AppendLine("            for (var i = 0; i < output.Length; i++)");
                builder.AppendLine("            {");
                builder.AppendLine("                var source = ReadInt32(metadata, i * 4);");
                builder.AppendLine("                if (source < 0 || source >= payload.Length) throw new System.InvalidOperationException(\"Invalid byte permutation index.\");");
                builder.AppendLine("                output[i] = payload[source];");
                builder.AppendLine("            }");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(12))
            {
                builder.AppendLine("        private static byte[] DecodeCodec12(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            var expected = checked(charCount * 2);");
                builder.AppendLine("            if (metadata.Length != 1 || payload.Length < expected) throw new System.InvalidOperationException(\"Invalid UInt64 packing payload.\");");
                builder.AppendLine("            var output = new byte[expected];");
                builder.AppendLine("            for (var i = 0; i < output.Length; i++) output[i] = (byte)(payload[i] ^ metadata[0]);");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(13))
            {
                builder.AppendLine("        private static byte[] DecodeCodec13(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            var expected = checked(charCount * 2);");
                builder.AppendLine("            if (metadata.Length != 1 || payload.Length < expected || payload.Length % 16 != 0) throw new System.InvalidOperationException(\"Invalid GUID packing payload.\");");
                builder.AppendLine("            var output = new byte[expected];");
                builder.AppendLine("            for (var i = 0; i < output.Length; i++) output[i] = (byte)(payload[i] ^ metadata[0]);");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(14))
            {
                builder.AppendLine("        private static byte[] DecodeCodec14(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            var expected = checked(charCount * 2);");
                builder.AppendLine("            if (metadata.Length != 1 || payload.Length != checked(expected + 1) || payload[payload.Length - 1] != 1) throw new System.InvalidOperationException(\"Invalid BigInteger packing payload.\");");
                builder.AppendLine("            var output = new byte[expected];");
                builder.AppendLine("            for (var i = 0; i < output.Length; i++) output[i] = (byte)(payload[i] ^ metadata[0]);");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(15))
            {
                builder.AppendLine("        private static byte[] DecodeCodec15(byte[] metadata, byte[] payload, int charCount)");
                builder.AppendLine("        {");
                builder.AppendLine("            var expected = checked(charCount * 2);");
                builder.AppendLine("            if (metadata.Length != 1 || payload.Length != checked(expected * 3)) throw new System.InvalidOperationException(\"Invalid junked payload.\");");
                builder.AppendLine("            var output = new byte[expected];");
                builder.AppendLine("            for (var i = 0; i < output.Length; i++) output[i] = (byte)(payload[i * 3] ^ metadata[0]);");
                builder.AppendLine("            return output;");
                builder.AppendLine("        }");
                builder.AppendLine();
            }
        }

        private static void AppendCommonHelpers(StringBuilder builder, ISet<byte> codecs)
        {
            if (codecs.Contains(2) || codecs.Contains(4))
            {
                builder.AppendLine("        private static void ApplyLcgXor(byte[] data, uint seed)");
                builder.AppendLine("        {");
                builder.AppendLine("            var state = seed;");
                builder.AppendLine("            for (var i = 0; i < data.Length; i++)");
                builder.AppendLine("            {");
                builder.AppendLine("                state = unchecked(state * 1664525u + 1013904223u);");
                builder.AppendLine("                data[i] ^= (byte)(state >> 24);");
                builder.AppendLine("            }");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            if (codecs.Contains(3) || codecs.Contains(4))
            {
                builder.AppendLine("        private static byte[] Decompress(byte[] payload)");
                builder.AppendLine("        {");
                builder.AppendLine("            using (var input = new System.IO.MemoryStream(payload))");
                builder.AppendLine("            using (var gzip = new System.IO.Compression.GZipStream(input, System.IO.Compression.CompressionMode.Decompress))");
                builder.AppendLine("            using (var output = new System.IO.MemoryStream())");
                builder.AppendLine("            {");
                builder.AppendLine("                gzip.CopyTo(output);");
                builder.AppendLine("                return output.ToArray();");
                builder.AppendLine("            }");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("        private static byte[] Clone(byte[] bytes)");
            builder.AppendLine("        {");
            builder.AppendLine("            var clone = new byte[bytes.Length];");
            builder.AppendLine("            System.Buffer.BlockCopy(bytes, 0, clone, 0, bytes.Length);");
            builder.AppendLine("            return clone;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static byte[] Slice(byte[] bytes, int offset, int length)");
            builder.AppendLine("        {");
            builder.AppendLine("            ValidateRange(offset, length, bytes.Length, \"slice\");");
            builder.AppendLine("            var result = new byte[length];");
            builder.AppendLine("            System.Buffer.BlockCopy(bytes, offset, result, 0, length);");
            builder.AppendLine("            return result;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static string StringFromUtf16Le(byte[] bytes, int charCount)");
            builder.AppendLine("        {");
            builder.AppendLine("            var chars = new char[charCount];");
            builder.AppendLine("            for (var i = 0; i < chars.Length; i++)");
            builder.AppendLine("            {");
            builder.AppendLine("                chars[i] = (char)(bytes[i * 2] | (bytes[i * 2 + 1] << 8));");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return new string(chars);");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static void WriteChar(byte[] target, int charIndex, ushort value)");
            builder.AppendLine("        {");
            builder.AppendLine("            var offset = charIndex * 2;");
            builder.AppendLine("            target[offset] = (byte)value;");
            builder.AppendLine("            target[offset + 1] = (byte)(value >> 8);");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static int ReadInt32(byte[] bytes, int offset)");
            builder.AppendLine("        {");
            builder.AppendLine("            ValidateRange(offset, 4, bytes.Length, \"int32\");");
            builder.AppendLine("            return bytes[offset] | (bytes[offset + 1] << 8) | (bytes[offset + 2] << 16) | (bytes[offset + 3] << 24);");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static uint ReadUInt32(byte[] bytes, int offset)");
            builder.AppendLine("        {");
            builder.AppendLine("            return unchecked((uint)ReadInt32(bytes, offset));");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static ushort ReadUInt16(byte[] bytes, int offset)");
            builder.AppendLine("        {");
            builder.AppendLine("            ValidateRange(offset, 2, bytes.Length, \"uint16\");");
            builder.AppendLine("            return (ushort)(bytes[offset] | (bytes[offset + 1] << 8));");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static uint ComputeFnv1a32(byte[] data)");
            builder.AppendLine("        {");
            builder.AppendLine("            unchecked");
            builder.AppendLine("            {");
            builder.AppendLine("                uint hash = 2166136261u;");
            builder.AppendLine("                for (var i = 0; i < data.Length; i++)");
            builder.AppendLine("                {");
            builder.AppendLine("                    hash ^= data[i];");
            builder.AppendLine("                    hash *= 16777619u;");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                return hash;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static void ValidateRange(int offset, int length, int totalLength, string name)");
            builder.AppendLine("        {");
            builder.AppendLine("            if (offset < 0 || length < 0 || offset > totalLength || length > totalLength - offset)");
            builder.AppendLine("            {");
            builder.AppendLine("                throw new System.InvalidOperationException(\"String resource \" + name + \" range is invalid.\");");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        private static void AppendEntryType(StringBuilder builder)
        {
            builder.AppendLine("        private sealed class Entry");
            builder.AppendLine("        {");
            builder.AppendLine("            public Entry(int token, int cacheIndex, int codecId, int flags, int decodedCharLength, int metadataOffset, int metadataLength, int payloadOffset, int payloadLength, uint checksum)");
            builder.AppendLine("            {");
            builder.AppendLine("                Token = token;");
            builder.AppendLine("                CacheIndex = cacheIndex;");
            builder.AppendLine("                CodecId = codecId;");
            builder.AppendLine("                Flags = flags;");
            builder.AppendLine("                DecodedCharLength = decodedCharLength;");
            builder.AppendLine("                MetadataOffset = metadataOffset;");
            builder.AppendLine("                MetadataLength = metadataLength;");
            builder.AppendLine("                PayloadOffset = payloadOffset;");
            builder.AppendLine("                PayloadLength = payloadLength;");
            builder.AppendLine("                Checksum = checksum;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            public int Token { get; private set; }");
            builder.AppendLine("            public int CacheIndex { get; private set; }");
            builder.AppendLine("            public int CodecId { get; private set; }");
            builder.AppendLine("            public int Flags { get; private set; }");
            builder.AppendLine("            public int DecodedCharLength { get; private set; }");
            builder.AppendLine("            public int MetadataOffset { get; private set; }");
            builder.AppendLine("            public int MetadataLength { get; private set; }");
            builder.AppendLine("            public int PayloadOffset { get; private set; }");
            builder.AppendLine("            public int PayloadLength { get; private set; }");
            builder.AppendLine("            public uint Checksum { get; private set; }");
            builder.AppendLine("        }");
        }

        private static string Quote(string value)
        {
            return Microsoft.CodeAnalysis.CSharp.SyntaxFactory.LiteralExpression(
                Microsoft.CodeAnalysis.CSharp.SyntaxKind.StringLiteralExpression,
                Microsoft.CodeAnalysis.CSharp.SyntaxFactory.Literal(value)).ToFullString();
        }
    }
}
